# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '删除')], verbose_name='状态'),
        ),
    ]
