# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-30 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=255, verbose_name='评论对象'),
        ),
    ]
